# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hp/end_game/end_game.cache/wt [current_project]
set_property parent.project_path C:/Users/hp/end_game/end_game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/hp/end_game/end_game.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/alu.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/clock_div.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/control.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/cpu.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/pc.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/reg.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/seven_seg.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/sram.v
  C:/Users/hp/end_game/end_game.srcs/sources_1/new/main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hp/end_game/end_game.srcs/constrs_1/new/my_constraint.xdc
set_property used_in_implementation false [get_files C:/Users/hp/end_game/end_game.srcs/constrs_1/new/my_constraint.xdc]


synth_design -top main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
